mdm_Location/MDM_Location/src/objects/MDM_Banner__c.object
<CustomObject>
    <description>MDM_Banner</description>
    <label>Banner</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_Configuration__c.object
<CustomObject>
    <description>MDM_Configuration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>This is for the configuration field(a) Name &amp; Value pairs. 
Name stored in Name and the  values stored here.</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MDM_Configuration</label>
    <nameField>
        <label>MDM_Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_Country__c.object
<CustomObject>
    <description>MDM_Country</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_Location__c.object
<CustomObject>
    <description>MDM_Location</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Address 1</description>
        <inlineHelpText>Address 1</inlineHelpText>
        <label>Address line 1:</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <description>Address 2</description>
        <inlineHelpText>Address 2</inlineHelpText>
        <label>Address line 2:</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_3__c</fullName>
        <description>Address 3</description>
        <inlineHelpText>Address 3</inlineHelpText>
        <label>Address line 3:</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Banner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Banner</description>
        <inlineHelpText>Banner</inlineHelpText>
        <label>Banner</label>
        <referenceTo>MDM_Banner__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country</description>
        <inlineHelpText>Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>MDM_Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DataOverrideFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag used to enable or disable the location data  enrichment (in BOOMI MDM) during the integration process.</description>
        <label>Data Override Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>Latitude</description>
        <inlineHelpText>Latitude</inlineHelpText>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LocationStatus__c</fullName>
        <description>Store Outlet Status Indicator</description>
        <inlineHelpText>Store Outlet Status Indicator</inlineHelpText>
        <label>Location Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclassified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Number__c</fullName>
        <description>Location Number</description>
        <inlineHelpText>Location Number</inlineHelpText>
        <label>Store Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Location Type [Emploee / Store]</description>
        <inlineHelpText>Emploee / Store</inlineHelpText>
        <label>Location Type</label>
        <picklist>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domicile</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <description>Longitude</description>
        <inlineHelpText>Longitude</inlineHelpText>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OwningCompany__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>OwningCompany</description>
        <inlineHelpText>OwningCompany</inlineHelpText>
        <label>Owning Company</label>
        <referenceTo>MDM_OwningCompany__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations_OwningCompany</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State/Province</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MDM_State__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MDM_State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store_Phone_Number__c</fullName>
        <description>Store Phone Number</description>
        <inlineHelpText>Store Phone Number</inlineHelpText>
        <label>Store Phone Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TradeChannel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Trade Channel</description>
        <inlineHelpText>Trade Channel</inlineHelpText>
        <label>TradeChannel</label>
        <referenceTo>MDM_TradeChannel__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TradeSubChannel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TradeSubChannel</description>
        <inlineHelpText>TradeSubChannel</inlineHelpText>
        <label>TradeSubChannel</label>
        <referenceTo>MDM_TradeSubChannel__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ValidateUpsert__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Submit for MDM validation. Based on this flag this new or updated record will be moved to stage for further validation.</description>
        <label>ValidateUpsert</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_OwningCompany__c.object
<CustomObject>
    <description>MDM_OwningCompany</description>
    <label>OwningCompany</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OwningCompanies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_Source__c.object
<CustomObject>
    <description>This object is to have he list of source for MDM.
When a record send to BOOMI MDM for mastering all records should have this reference,
To determine, who is the contributor for the system of record source.</description>
    <label>MDM_Source</label>
    <nameField>
        <label>MDM_Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_State__c.object
<CustomObject>
    <description>MDM_State</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>MDM_Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_TradeChannel__c.object
<CustomObject>
    <description>MDM_TradeChannel</description>
    <label>TradeChannel</label>
    <nameField>
        <label>TradeChannel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TradeChannels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/classes/MDM_AddLocationsExtTest.cls
@istest
public class MDM_AddLocationsExtTest {
    @istest
    Static void MDM_AddLocationsExt()
    {
        MDM_configuration__c mdc0 = new MDM_configuration__c();
        mdc0.name='DeleteStageRecordsBeforeInsert';
        mdc0.Value__c = 'true' ;
        insert mdc0;
        
        MDM_configuration__c mdc = new MDM_configuration__c();
        mdc.name='MDM_IntegrationUser';
        mdc.Value__c = 'Ramakrishnan.Ramadur@crossmark.com.mdmlocuat' ;
        insert mdc;
        
        MDM_configuration__c mdc1 = new MDM_configuration__c();
        mdc1.name='BatchUploadHeaderLine';
        mdc1.Value__c = 'Location Type|Location Number|Location Status|Location Name|Address line 1:|Address line 2:|Address line 3:|City|State|Country|Postal Code|Phone Number|Latitude|Longitude|Owning Company|Chain|TradeChannel|TradeSubchannel|IdFromSource' ;
        insert mdc1;
        
        MDM_configuration__c mdc2 = new MDM_configuration__c();
        mdc2.name='BatchUploadDelimiter';
        mdc2.Value__c = '|' ;
        insert mdc2;
        
        MDM_Source__c lsc = new MDM_Source__c();
        lsc.Name = 'SalesForce1';
        insert(lsc);
        
        MDM_Source__c lsc1 = new MDM_Source__c();
        lsc1.Name = 'Coke';
        insert(lsc1);
        
        MDM_Country__C cnt = new MDM_Country__C();
        cnt.Name = 'UNITED STATES';
        insert(cnt);
        
        MDM_State__C sta = new MDM_State__C();
        sta.Name = 'AK';
        sta.Country__c = cnt.id;
        insert(sta);
        
        MDM_Banner__c bnr= new MDM_Banner__c();
        bnr.Name = 'TEST_BANNER';
        insert(bnr);
        
        MDM_OwningCompany__c ocp = new MDM_OwningCompany__c();
        ocp.Name = 'TEST_OWNINGCOMPANY';
        insert(ocp);
        
        MDM_TradeChannel__c tch = new MDM_TradeChannel__c();
        tch.Name = 'TEST_TRADECHANNEL';
        insert(tch);
        
        string loc_csvFilenameString ='TESTFILE123456789123456789123456789.CSV';
        string loc_locationListName='TEST_NAMELIST';
        string loc_LocationSourceValue = lsc.id;
        
        MDM_Location__c oLocation = new MDM_Location__c();
        oLocation.name = 'TEST_NAME';
        oLocation.Address_1__c = 'TEST Home Address_1' ;
        oLocation.Address_2__c = 'TEST Home Address_2__c' ;
        oLocation.Address_3__c = 'TEST Home Address_3__c' ;
        oLocation.Banner__c   = bnr.id;
        oLocation.City__c     = 'TEST_City';
        oLocation.Country__c  = cnt.id;
        oLocation.Latitude__c     = 0.0;
        oLocation.Location_Number__c  = '1001';
        oLocation.Location_Type__c    = 'Business';
        oLocation.Longitude__c    = 0.0;
        oLocation.OwningCompany__c   = ocp.id;
        oLocation.Postal_Code__c  = '452369';
        oLocation.State__c    = sta.id; 
        oLocation.Store_Phone_Number__c   = '12345896'; 
        oLocation.TradeChannel__c     = tch.id;
        //oLocation.TradeSubChannel__c  = '';
        oLocation.LocationStatus__c  = 'OPEN';
        oLocation.DataOverrideFlag__c  = true; 
        oLocation.ValidateUpsert__c  = true; 
        //ApexPages.StandardController controller1;
        //controller1 =  ApexPages.StandardController(oLocation);
        PageReference pageRef = Page.MDM_AddLocation;
        Test.setCurrentPage(pageRef);
        Test.startTest();
        //insert oLocation;
        ApexPages.StandardController sc = new ApexPages.standardController(oLocation);
        MDM_Location_AddLocationsExt alxt = new MDM_Location_AddLocationsExt(sc);
        alxt.saveAndReturn();
        alxt.Save();
        alxt.Cancel();
        //MDM_Source__c srcID = [SELECT Id FROM MDM_Source__c where Name = 'SalesForce'];
        //srcID.Name='SalesForce1';
        MDM_Source__c lsc11 = new MDM_Source__c();
        lsc11.Name = 'SalesForce';
        insert(lsc11);
        alxt.saveAndReturn();
        alxt.Save();
        alxt.Cancel();
        Test.stopTest();
         
    } 
    /*@istest
    Static void MDM_AddLocationsExtException()
    {
        MDM_configuration__c mdc0 = new MDM_configuration__c();
        mdc0.name='DeleteStageRecordsBeforeInsert';
        mdc0.Value__c = 'true' ;
        insert mdc0;
        
        MDM_configuration__c mdc = new MDM_configuration__c();
        mdc.name='MDM_IntegrationUser';
        mdc.Value__c = 'Ramakrishnan.Ramadur@crossmark.com.mdmlocuat' ;
        insert mdc;
        
        MDM_configuration__c mdc1 = new MDM_configuration__c();
        mdc1.name='BatchUploadHeaderLine';
        mdc1.Value__c = 'Location Type|Location Number|Location Status|Location Name|Address line 1:|Address line 2:|Address line 3:|City|State|Country|Postal Code|Phone Number|Latitude|Longitude|Owning Company|Chain|TradeChannel|TradeSubchannel|IdFromSource' ;
        insert mdc1;
        
        MDM_configuration__c mdc2 = new MDM_configuration__c();
        mdc2.name='BatchUploadDelimiter';
        mdc2.Value__c = '|' ;
        insert mdc2;
        
        MDM_Source__c lsc = new MDM_Source__c();
        lsc.Name = 'SalesForce';
        insert(lsc);
        
        MDM_Source__c lsc1 = new MDM_Source__c();
        lsc1.Name = 'Coke';
        insert(lsc1);
        
        MDM_Country__C cnt = new MDM_Country__C();
        cnt.Name = 'UNITED STATES';
        insert(cnt);
        
        MDM_State__C sta = new MDM_State__C();
        sta.Name = 'AK';
        sta.Country__c = cnt.id;
        insert(sta);
        
        MDM_Banner__c bnr= new MDM_Banner__c();
        bnr.Name = 'TEST_BANNER';
        insert(bnr);
        
        MDM_OwningCompany__c ocp = new MDM_OwningCompany__c();
        ocp.Name = 'TEST_OWNINGCOMPANY';
        insert(ocp);
        
        MDM_TradeChannel__c tch = new MDM_TradeChannel__c();
        tch.Name = 'TEST_TRADECHANNEL';
        insert(tch);
        
        string loc_csvFilenameString ='TESTFILE123456789123456789123456789.CSV';
        string loc_locationListName='TEST_NAMELIST';
        string loc_LocationSourceValue = lsc.id;
        
        MDM_Location__c oLocation = new MDM_Location__c();
        oLocation.name = 'TEST_NAME';
        oLocation.Address_1__c = 'TEST Home Address_1' ;
        oLocation.Address_2__c = 'TEST Home Address_2__c' ;
        oLocation.Address_3__c = 'TEST Home Address_3__c' ;
        oLocation.Banner__c   = bnr.id;
        oLocation.City__c     = 'TEST_City';
        oLocation.Country__c  = cnt.id;
        oLocation.Latitude__c     = 0.0;
        oLocation.Location_Number__c  = '1001';
        oLocation.Location_Type__c    = 'Business';
        oLocation.Longitude__c    = 0.0;
        oLocation.OwningCompany__c   = ocp.id;
        oLocation.Postal_Code__c  = '452369';
        oLocation.State__c    = sta.id; 
        oLocation.Store_Phone_Number__c   = '12345896'; 
        oLocation.TradeChannel__c     = tch.id;
        //oLocation.TradeSubChannel__c  = '';
        oLocation.LocationStatus__c  = 'OPEN';
        oLocation.DataOverrideFlag__c  = true; 
        oLocation.ValidateUpsert__c  = true; 
        //ApexPages.StandardController controller1;
        //controller1 =  ApexPages.StandardController(oLocation);
        PageReference pageRef = Page.AddLocation;
        Test.setCurrentPage(pageRef);
        Test.startTest();
        insert oLocation;
        ApexPages.StandardController sc = new ApexPages.standardController(oLocation);
        MDM_AddLocationsExt alxt = new MDM_AddLocationsExt(sc);
        alxt.saveAndReturn();
        alxt.Save();
        alxt.Cancel();
        Test.stopTest();
     
    } 
    */
}