mdm_Location/MDM_Location/src/objects/MDM_Location__c.object
<CustomObject>
    <description>MDM_Location</description>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SourceSystem</description>
        <label>SourceSystem</label>
        <referenceTo>MDM_Source__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/objects/MDM_Source__c.object
<CustomObject>
    <description>This object is to have he list of source for MDM.
When a record send to BOOMI MDM for mastering all records should have this reference,
To determine, who is the contributor for the system of record source.</description>
    <label>MDM_Source</label>
    <nameField>
        <label>MDM_Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDM_Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdm_Location/MDM_Location/src/classes/MDM_Location_AddLocationsExt.cls
public with sharing class MDM_Location_AddLocationsExt {
    private ApexPages.StandardController controller;
    
    public MDM_Location_AddLocationsExt(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    public PageReference saveAndReturn()
    {
        PageReference cancel = controller.cancel();
        try
        {
            MDM_Location__c t = (MDM_Location__c)controller.getRecord();
            MDM_Source__c srcID = [SELECT Id FROM MDM_Source__c where Name = 'SalesForce'];
            t.SourceSystem__c =  srcID.ID;
            if(srcID == null)
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'MDM Source missing SalesForce as a Source.');
                ApexPages.addMessage(myMsg);
                return null;
            }
            controller.save();
            
        }
        catch(Exception e){
            System.debug('==Exception Message==='+e.getMessage());
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
            ApexPages.addMessage(myMsg);
            return null;
        }
        return cancel;
    }
    public PageReference Cancel()
    {
        PageReference page = new PageReference('/');
        page.setRedirect(true);
        return page;
    }
    public pageReference save(){    
        PageReference pageRef = controller.save();
        Map<string,string> URLParameters = ApexPages.currentPage().getParameters();
        if(URLParameters.containsKey('retURL')){
            pageRef = new PageReference(URLParameters.get('retURL'));
        }       
        return pageRef;
    }  
}